### ISSUE TITLE
BMI parameter

### ISSUE THREAD

**Issue by RobertWojtowicz** [davidkroell/bodycomposition#9] opened 2020-12-15 21:03 UTC
Hi,

I miss the BMI parameter transfer to Garmin Connect.
Can you check if there is such a possibility?

Best Reagards,
Robert

**Comment by davidkroell** [comment] 2021-01-24 18:14
Hi @RobertWojtowicz I already experienced this, but I cannot find the root cause yet.

It seems like the problem is in Garmin connect.
At the specific weight-ins the BMI is not shown, but when you use the weekly/monthly view, the average BMI shows up (maybe internally calculated).

It seems that this is also not possible in https://github.com/kochka/WeightLogger.

Regards

**Comment by davidkroell** [comment] 2021-04-30 17:25
Hi @RobertWojtowicz, may I close this?

**Comment by RobertWojtowicz** [comment] 2021-11-01 18:03
Hi @davidkroell 

Could you have a look at this? I guess you could add BMI: 
https://github.com/jaroslawhartman/withings-garmin-v2/pull/19

In a newer version:
https://github.com/jaroslawhartman/withings-sync/blob/master/withings_sync/fit.py

Best Reagards,
Robert

**Comment by davidkroell** [comment] 2021-11-02 19:14
Hi @RobertWojtowicz I'm currently looking into it. The base library I use will need an update.

I'm working on that right now.

Best regards

**Comment by RobertWojtowicz** [comment] 2021-11-02 19:16
> rrently looking into it. The base library I use will need an update

Thank you very much

**Comment by RobertWojtowicz** [comment] 2021-11-03 16:34
Analyzing the BMI sync case, I found this, maybe it can help to solve the problem of Caloric Intake sync (https://github.com/davidkroell/bodycomposition/issues/11):
https://github.com/jaroslawhartman/withings-sync/blob/master/withings_sync/fit.py 
You can see such fields:
(7, FitBaseType.uint16, basal_met, 4), 
(9, FitBaseType.uint16, active_met, 4), >> caloriesActiveMet (Caloric Intake ?)

The case looks old:
https://forums.garmin.com/apps-software/mobile-apps-web/f/garmin-connect-web/43018/body-fat-manual-input/307510

Best Regards,
Robert

**Comment by davidkroell** [comment] 2021-11-03 16:46
Hi,

of course this could be also the case but I'm not sure if your code snippet is correct.
You maybe mix something up here.

I think the `active_met` is the burnt calories rather than the calories eaten.

Maybe it is also possible to implement this using a similar fix, but I'll have to investigate this further

BR,
David

**Comment by RobertWojtowicz** [comment] 2021-11-03 21:51
> Maybe it is also possible to implement this using a similar fix, but I'll have to investigate this further
> 
> BR, David

Thank you very much for your support, I am patiently waiting for the fixes  :)
I adapted Xiaomi scale sync with your amazing module, it works perfectly :)

Best Regards,
Robert

**Comment by davidkroell** [comment] 2021-11-21 10:08
Part of the version [v2.2.0](https://github.com/davidkroell/bodycomposition/releases/tag/v2.2.0)

Regards,
David

**Closed as completed by davidkroell** 2021-11-21 10:08 UTC
